# Generated by Django 5.2.7 on 2025-10-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_code_snippet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
